"""Creature-subtype vocabulary + subject-resolution constants for signal extraction.

CREATURE_SUBTYPES is self-derived from Scryfall bulk type_lines (creature faces only,
split on // first so adventure/split spell faces never leak "sorcery"/"instant").
It is the allowlist that validates a captured tribal subject so junk captures (a clone
clause, a flavor noun) resolve to nothing rather than a false-positive kindred signal.

Regenerate after large set releases (the one-off: load bulk -> for creature faces,
split_type_line -> subtypes, lowercased, len>=3, alpha, minus NON_SUBJECT_WORDS).
New creature types are rare, so drift is slow.
"""

from __future__ import annotations

# Card-type / spell-type / noise nouns that must NEVER become a tribal subject —
# they fall through to the generic key instead (e.g. "creatures you control").
# Articles/stopwords and the five basic LAND types (CR 305.6 — NOT creature types,
# CR 205.3m) are denied here as defense-in-depth: _resolve_subject checks this set
# BEFORE the vocab, so even if CREATURE_SUBTYPES regresses, "the spell you cast"
# (→'the', which served ~11,458 cards) and "a Forest you control" can't mint a tribe.
NON_SUBJECT_WORDS: frozenset[str] = frozenset(
    {
        "creature",
        "creatures",
        "permanent",
        "permanents",
        "token",
        "tokens",
        "spell",
        "spells",
        "card",
        "cards",
        "nonland",
        "noncreature",
        "nontoken",
        "color",
        "colors",
        "instant",
        "instants",
        "sorcery",
        "sorceries",
        "battle",
        # articles / stopwords (an article is not a subtype)
        "the",
        "a",
        "an",
        "this",
        "that",
        "another",
        "other",
        "your",
        "their",
        "its",
        "each",
        "target",
        # basic land types (CR 305.6) — land, not creature, types
        "plains",
        "island",
        "swamp",
        "mountain",
        "forest",
        # not the two-word creature type "Time Lord"; bare "time" is noise
        "time",
    }
)

# Card-type subjects we DO accept (type-matters card-type variant); these map to a
# card_type search rather than a kindred subtype search.
CARD_TYPE_SUBJECTS: frozenset[str] = frozenset(
    {
        "artifact",
        "enchantment",
        "land",
        "planeswalker",
        "equipment",
        "aura",
        "vehicle",
    }
)

# Irregular / partial-plural singularization. The (\w+?)s? capture can emit a partial
# plural ("Elve", "Dwarve") because the s? swallows the trailing s; map those to the
# real singular so flagship tribes (Magda->dwarf) don't silently drop.
IRREGULAR_SINGULAR: dict[str, str] = {
    "elves": "elf",
    "elve": "elf",
    "dwarves": "dwarf",
    "dwarve": "dwarf",
    "wolves": "wolf",
    "wolve": "wolf",
    "thieves": "thief",
    "thieve": "thief",
    "knives": "knife",
    "leaves": "leaf",
    "faeries": "faerie",
    "faerie": "faerie",
    "mice": "mouse",
    "wolfs": "wolf",
    "zombies": "zombie",
    "berries": "berry",
    "allies": "ally",
    "armies": "army",
    "fungi": "fungus",
    "djinn": "djinn",
    "efreet": "efreet",
    "sphinxes": "sphinx",
    "sphinx": "sphinx",
    "homunculi": "homunculus",
    "octopi": "octopus",
}

CREATURE_SUBTYPES: frozenset[str] = frozenset(
    {
        "advisor",
        "aetherborn",
        "alicorn",
        "alien",
        "ally",
        "angel",
        "antelope",
        "ape",
        "archer",
        "archon",
        "armadillo",
        "armored",
        "army",
        "art",
        "artificer",
        "artist",
        "assassin",
        "astartes",
        "athlete",
        "atog",
        "aurochs",
        "autobot",
        "avatar",
        "azra",
        "background",
        "baddest",
        "badger",
        "barbarian",
        "bard",
        "basilisk",
        "bat",
        "bear",
        "beast",
        "beaver",
        "beeble",
        "beholder",
        "berserker",
        "biggest",
        "bird",
        "bison",
        "boar",
        "book",
        "boxer",
        "brainiac",
        "bringer",
        "brushwagg",
        "bureaucrat",
        "camel",
        "capybara",
        "carrier",
        "cat",
        "centaur",
        "cephalid",
        "chameleon",
        "champion",
        "chef",
        "chicken",
        "child",
        "chimera",
        "citizen",
        "clamfolk",
        "cleric",
        "clown",
        "clue",
        "cockatrice",
        "construct",
        "cow",
        "coward",
        "coyote",
        "crab",
        "crocodile",
        "custodes",
        "cyberman",
        "cyborg",
        "cyclops",
        "dalek",
        "dauthi",
        "deer",
        "demigod",
        "demon",
        "designer",
        "detective",
        "devil",
        "dinosaur",
        "djinn",
        "doctor",
        "dog",
        "donkey",
        "dragon",
        "drake",
        "dreadnought",
        "drix",
        "drone",
        "druid",
        "dryad",
        "dwarf",
        "echidna",
        "efreet",
        "egg",
        "elder",
        "eldrazi",
        "elemental",
        "elephant",
        "elf",
        "elk",
        "elves",
        "employee",
        "equipment",
        "eternal",
        "etiquette",
        "eye",
        "faerie",
        "ferret",
        "fish",
        "flagbearer",
        "food",
        "fox",
        "fractal",
        "frog",
        "fungus",
        "gamer",
        "gamma",
        "gargoyle",
        "giant",
        "giraffe",
        "gith",
        "glimmer",
        "gnoll",
        "gnome",
        "goat",
        "goblin",
        "god",
        "golem",
        "gorgon",
        "grandchild",
        "gremlin",
        "griffin",
        "guest",
        "gus",
        "hag",
        "halfling",
        "hamster",
        "harpy",
        "hatificer",
        "hawk",
        "head",
        "hedgehog",
        "hellion",
        "hero",
        "hippo",
        "hippogriff",
        "homarid",
        "homunculus",
        "horror",
        "horse",
        "human",
        "hydra",
        "hyena",
        "illusion",
        "imp",
        "incarnation",
        "inhuman",
        "inkling",
        "inquisitor",
        "insect",
        "jackal",
        "jellyfish",
        "judge",
        "juggernaut",
        "kangaroo",
        "kavu",
        "killbot",
        "kirin",
        "kithkin",
        "knight",
        "koala",
        "kobold",
        "kor",
        "kraken",
        "kree",
        "lady",
        "lamia",
        "lammasu",
        "lander",
        "leech",
        "lemur",
        "leviathan",
        "lhurgoyf",
        "licid",
        "lizard",
        "lobster",
        "locus",
        "lord",
        "mammoth",
        "manticore",
        "masticore",
        "mercenary",
        "merfolk",
        "metathran",
        "mime",
        "minion",
        "minotaur",
        "mite",
        "mole",
        "monger",
        "mongoose",
        "monk",
        "monkey",
        "moogle",
        "moonfolk",
        "mount",
        "mouse",
        "mummy",
        "mutant",
        "myr",
        "mystic",
        "nastiest",
        "nautilus",
        "necron",
        "nephilim",
        "nightmare",
        "nightstalker",
        "ninja",
        "noble",
        "noggle",
        "nomad",
        "nymph",
        "octopus",
        "officer",
        "ogre",
        "ooze",
        "orc",
        "orgg",
        "otter",
        "ouphe",
        "oyster",
        "pangolin",
        "paratrooper",
        "peasant",
        "pegasus",
        "penguin",
        "performer",
        "pest",
        "phelddagrif",
        "phoenix",
        "phyrexian",
        "pilot",
        "pirate",
        "plant",
        "platypus",
        "pony",
        "porcupine",
        "possum",
        "praetor",
        "primarch",
        "processor",
        "proper",
        "rabbit",
        "raccoon",
        "ranger",
        "rat",
        "rebel",
        "reflection",
        "rhino",
        "rigger",
        "robot",
        "rogue",
        "sable",
        "saga",
        "salamander",
        "samurai",
        "sand",
        "saproling",
        "satyr",
        "scarecrow",
        "scientist",
        "scorpion",
        "scout",
        "seal",
        "serpent",
        "shade",
        "shaman",
        "shapeshifter",
        "shark",
        "sheep",
        "ship",
        "shrine",
        "siren",
        "skeleton",
        "skrull",
        "skunk",
        "slith",
        "sliver",
        "sloth",
        "slug",
        "snail",
        "snake",
        "soldier",
        "soltari",
        "sorcerer",
        "spawn",
        "specter",
        "spellshaper",
        "sphinx",
        "spider",
        "spike",
        "spirit",
        "splinter",
        "sponge",
        "spuzzem",
        "spy",
        "squid",
        "squirrel",
        "starfish",
        "surrakar",
        "survivor",
        "symbiote",
        "synth",
        "thalakos",
        "thopter",
        "thrull",
        "tiefling",
        "townsfolk",
        "toy",
        "treasure",
        "tree",
        "treefolk",
        "trilobite",
        "troll",
        "turtle",
        "tyranid",
        "unicorn",
        "utrom",
        "vampire",
        "vampyre",
        "varmint",
        "vedalken",
        "villain",
        "volver",
        "waiter",
        "wall",
        "walrus",
        "warlock",
        "warrior",
        "weasel",
        "weird",
        "werewolf",
        "whale",
        "wizard",
        "wolf",
        "wolverine",
        "wombat",
        "worm",
        "wraith",
        "wrestler",
        "wurm",
        "yeti",
        "zombie",
        "zonian",
        "zubera",
    }
)

# Race/iconic creature tribes a commander can be built around purely by BEING one —
# the subtype characteristic (CR 205.3) is what tribal cards reference (CR 702.38a),
# independent of oracle text. Originally derived from creature subtypes with >=8
# tribal-support cards, MINUS generic class types (human/soldier/warrior/wizard/cleric/
# rogue/...), which are near-ubiquitous and only become a build-around with explicit
# oracle support. The second block adds iconic RACES with deep creature pools (>=16
# creatures) but no lords — for a Kraken / Wolf / Shade / Yeti commander you still build
# a pile of the tribe, so the membership signal surfaces it. Class types stay excluded.
# Used to emit a LOW-confidence own-subtype signal so a vanilla Dragon/Kraken/Beast
# surfaces its tribe instead of reading as zero-signal.
TRIBAL_SUBTYPES: frozenset[str] = frozenset(
    {
        "ally",
        "angel",
        "bird",
        "cat",
        "demon",
        "dinosaur",
        "dragon",
        "elemental",
        "elf",
        "faerie",
        "giant",
        "goblin",
        "kithkin",
        "knight",
        "merfolk",
        "mount",
        "phyrexian",
        "pirate",
        "rat",
        "sliver",
        "spider",
        "spirit",
        "squirrel",
        "vampire",
        "zombie",
        # Deep-pool races with no lords but real "build a pile of this type" identity.
        "beast",
        "horror",
        "insect",
        "snake",
        "hydra",
        "wurm",
        "treefolk",
        "ooze",
        "fungus",
        "elephant",
        "frog",
        "kraken",
        "wolf",
        "werewolf",
        "shade",
        "yeti",
        "drake",
        "dryad",
        "plant",
        "lizard",
        "minotaur",
        "ogre",
        "dwarf",
        "golem",
        "eldrazi",
        # More iconic races with buildable pools + dedicated commanders. Samurai is a
        # flavor-tribe (Kamigawa) with its own commanders, unlike the truly-ubiquitous
        # generic classes (Warrior/Soldier/Wizard) that stay excluded.
        "griffin",
        "leviathan",
        "serpent",
        "samurai",
        "wall",
        "sphinx",
        "centaur",
        "satyr",
        "devil",
        "imp",
        "construct",
        "robot",
        "orc",
        "illusion",
        "dog",
        "mutant",
        "crab",
        "octopus",
        "bat",
        "turtle",
        "bear",
        "salamander",
        "gnome",
        "scarecrow",
        "gargoyle",
        "phoenix",
        "unicorn",
        "rhino",
        "boar",
        "ape",
    }
)
